# Generated by Django 4.2.14 on 2024-07-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=255)),
                ("picture_url", models.URLField(blank=True, null=True)),
                ("status_message", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
